import { useState, useEffect } from "react";
import { ArrowLeft, Heart, Ticket, Star, Info, ChevronRight, Landmark, TramFront, Shirt, ExternalLink, Waves, Music, Eye, Moon, Ship, Sun, Bus, MapPin, UtensilsCrossed, ChefHat, Fish, Clock, Camera, Zap, AlertTriangle, Check, Sparkles, Navigation } from "lucide-react";

const C = { ink:"#0F172A", inkSoft:"#475569", inkMute:"#94A3B8", line:"#E2E8F0", soft:"#F8FAFC", blue:"#1D4ED8", blueSoft:"#DBEAFE", ok:"#059669", okSoft:"#D1FAE5", warn:"#D97706", warnSoft:"#FEF3C7", gold:"#C59D5F", goldSoft:"#FBF5EB", dark:"#0B1220", danger:"#E11D48" };
const fd = "'Plus Jakarta Sans',system-ui,sans-serif";
const fs = "'Inter',system-ui,sans-serif";

const D = {
  hagia:{gallery:["/hagia.jpg","/hagia-2.jpg","/hagia-3.jpg","/hagia-4.jpg","/hagia-5.jpg"],reviews:"48K+",whyGo:"This is not just a mosque. It's one of the most powerful buildings in the world. Standing inside, you'll see Christian mosaics and Islamic calligraphy in the same space — something you won't find anywhere else. If you only visit one place in Istanbul, make it this.",facts:[{l:"From",v:"€25"},{l:"Duration",v:"45–90 min"},{l:"Area",v:"Sultanahmet"},{l:"Rating",v:"4.9 ⭐"}],bestTime:["Go before 09:00 for a calm experience","Sunset = best light for photos","Avoid Friday 12:00–14:30 (prayer closure)"],skipStrategy:{free:"Lines can reach 60–90 minutes in peak season. Skip-the-line ticket is the smart move.",premium:"Best ticket combo + exact timing for zero wait"},photoSpot:{free:"Stand near the central marble circle for the full dome shot. Use wide angle."},timeReality:{quick:"30 min (not recommended)",ideal:"60–90 min",note:"Most people rush this — don't."},goodToKnow:["Closed during prayer times","Dress modestly (scarf required for women)","Tourist entrance is different from prayer entrance","No loud talking inside"],commonMistakes:["Entering from the wrong gate","Visiting at noon (crowded & hot)","Skipping the upper gallery","Not bringing a scarf"],smartPrice:{gate:"€25 regular",better:"Skip-the-line + guide",why:"No waiting + you'll need context inside"},nearby:["basilica","topkapi"],comboTip:"Pair with Basilica Cistern (2 min away) + Blue Mosque (3 min)"},
  basilica:{gallery:["/basilica.jpg","/basilica-2.jpg","/basilica-3.jpg","/basilica-4.jpg"],reviews:"32K+",whyGo:"Walking into this underground world feels unreal. Columns rise from the water, lights reflect everywhere, and the silence hits differently. It's short, but unforgettable.",facts:[{l:"From",v:"€20"},{l:"Duration",v:"45–60 min"},{l:"Area",v:"Sultanahmet"},{l:"Rating",v:"4.8 ⭐"}],bestTime:["After 15:00 for fewer crowds","Weekday mornings are quietest","Night sessions have special lighting"],skipStrategy:{free:"Queues can hit 30–45 min. Buy from the official seller online.",premium:"Day vs night slot strategy + best ticket window"},photoSpot:{free:"The Medusa head columns and the main reflection walkway are the key shots."},timeReality:{quick:"20 min (too fast)",ideal:"45–60 min",note:"Take your time — the atmosphere is the whole point."},goodToKnow:["Cool underground — welcome break in summer","Small café inside near the exit","No flash photography","Closes briefly between day and night sessions"],commonMistakes:["Not booking ahead (long queue)","Rushing through in 15 min","Missing the Medusa columns at the back","Paying more at night without knowing"],smartPrice:{gate:"€20 day / €30 night",better:"Day ticket with skip-the-line",why:"Same cistern, lower price, less wait"},nearby:["hagia","topkapi"],comboTip:"5 min walk from Hagia Sophia — do them back to back"},
  topkapi:{gallery:["/topkapi.jpg","/topkapi-2.jpg","/topkapi-3.jpg","/topkapi-4.jpg"],reviews:"41K+",whyGo:"This is not one building. It's courtyards, kitchens, treasures, and secrets. You're literally walking through the daily life of sultans. This is where history becomes real.",facts:[{l:"From",v:"€30"},{l:"Duration",v:"2.5–3.5h"},{l:"Area",v:"Sultanahmet"},{l:"Rating",v:"4.9 ⭐"}],bestTime:["Arrive at 09:00 opening — gets crowded by 11:00","Treasury is best first (before tour groups)","Closed on Tuesdays"],skipStrategy:{free:"The Harem requires a separate ticket. Combined ticket saves money and time.",premium:"Optimal route through 4 courtyards + Harem timing hack"},photoSpot:{free:"Fourth courtyard terrace has the best Bosphorus panorama."},timeReality:{quick:"1.5h (Treasury + courtyard only)",ideal:"3–3.5h (full palace + Harem)",note:"Give it the time. This is a half-day highlight."},goodToKnow:["Closed on Tuesdays","Harem needs separate ticket — buy combo","Comfortable shoes essential","Audio guide recommended for context"],commonMistakes:["Going on Tuesday (closed)","Skipping the Harem","Not buying combo ticket","Underestimating the time needed"],smartPrice:{gate:"€30 palace only",better:"Combined: Palace + Harem",why:"Harem is the most interesting part"},nearby:["hagia","basilica"],comboTip:"Walk through Gülhane Park on the way in"},
  cruise:{gallery:["/cruise.jpg","/cruise-2.jpg","/cruise-3.jpg","/cruise-4.jpg"],reviews:"28K+",whyGo:"This is the easiest way to understand Istanbul. Europe on one side, Asia on the other. It's relaxing, scenic, and 100% worth it.",facts:[{l:"From",v:"€18"},{l:"Duration",v:"1.5–2h"},{l:"Area",v:"Eminönü"},{l:"Rating",v:"4.7 ⭐"}],bestTime:["Late afternoon for golden hour","Sunset departures are most popular","Avoid midday in summer (hot on deck)"],skipStrategy:{free:"Book the late afternoon slot. Confirm pier location before heading out.",premium:"Best deck position + which cruise company to choose"},photoSpot:{free:"Open upper deck, right side going up = European shore palaces."},timeReality:{quick:"1h short cruise (limited)",ideal:"2h full Bosphorus cruise",note:"The longer cruise is worth the extra time."},goodToKnow:["Bring a light jacket — breezy on water","Small café usually on board","Some cruises stop on the Asian side","Confirm exact pier: Eminönü or Kabataş"],commonMistakes:["Going to the wrong pier","Sitting inside instead of on deck","Booking the shortest cruise","Not checking sunset time"],smartPrice:{gate:"€18 standard",better:"Sunset cruise with open deck",why:"Same price range, dramatically better experience"},nearby:["galata","dolma"],comboTip:"Galata Tower before, then sunset cruise = perfect evening"},
  hammam:{gallery:["/hammam.jpg","/hammam-2.jpg","/hammam-3.jpg","/hammam-4.jpg"],reviews:"18K+",whyGo:"Equal parts ritual, culture, and reward. Not just relaxation — a centuries-old tradition that leaves you completely renewed. You'll regret skipping this.",facts:[{l:"From",v:"€45"},{l:"Duration",v:"60–90 min"},{l:"Area",v:"Various"},{l:"Rating",v:"4.8 ⭐"}],bestTime:["Morning sessions are calmest","Weekdays have fewer tourists","Check gender-specific hours before going"],skipStrategy:{free:"Book the classic scrub + foam package at a historic hammam.",premium:"Which hammam is best for your style + insider tips"},photoSpot:{free:"The marble heated platform (göbektaşı) is the iconic shot."},timeReality:{quick:"45 min (scrub only)",ideal:"90 min (full traditional)",note:"Don't rush it — the experience is the pace."},goodToKnow:["Peştamal (wrap) provided","Swimwear optional underneath","Separate sections for men and women","Bring a plastic bag for wet items"],commonMistakes:["Choosing a tourist-trap hammam","Not checking gender hours","Rushing through the experience","Skipping the foam massage"],smartPrice:{gate:"€45+ walk-in",better:"Pre-booked traditional package",why:"Better price + guaranteed slot at peak times"},nearby:["hagia","basilica"],comboTip:"Perfect morning activity before a day of sightseeing"},
  galata:{gallery:["/galata.jpg","/galata-2.jpg","/galata-3.jpg","/galata-4.jpg"],reviews:"35K+",whyGo:"Climb up and you'll see the entire city — Bosphorus, mosques, rooftops. It's the kind of view that makes you stop and just look.",facts:[{l:"From",v:"€15"},{l:"Duration",v:"30–45 min"},{l:"Area",v:"Beyoğlu"},{l:"Rating",v:"4.6 ⭐"}],bestTime:["Late afternoon for best light","Night-museum session for city lights","Clear days only — fog ruins the view"],skipStrategy:{free:"Book ahead online — queues spike before sunset.",premium:"Day vs night session strategy + crowd avoidance"},photoSpot:{free:"360° observation deck. Every angle is good — bring wide lens."},timeReality:{quick:"15 min (deck only)",ideal:"30–45 min (museum + deck + café)",note:"Quick but worth savoring the view."},goodToKnow:["Elevator inside","Open-air deck can get windy","Photography excellent from every angle","Walk down through Galata streets after"],commonMistakes:["Going on a cloudy day","Arriving right at sunset (longest queue)","Not exploring Galata streets after","Missing the night-session option"],smartPrice:{gate:"€15 standard",better:"Pre-booked timed slot",why:"Skip the queue + guaranteed entry"},nearby:["cruise","dolma"],comboTip:"Tower → walk down to Karaköy → sunset cruise from pier"},
  dolma:{gallery:["/dolma.jpg","/dolma-2.jpg","/dolma-3.jpg","/dolma-4.jpg"],reviews:"29K+",whyGo:"Crystal chandeliers, huge halls, insane details. It feels more like Paris than Istanbul — and that's exactly why it stands out.",facts:[{l:"From",v:"€28"},{l:"Duration",v:"2–2.5h"},{l:"Area",v:"Beşiktaş"},{l:"Rating",v:"4.7 ⭐"}],bestTime:["Morning timed entry is calmest","Avoid Mondays (closed)","Midweek visits have shortest waits"],skipStrategy:{free:"Prebook timed entry — walk-up queues can be an hour.",premium:"Optimal route through Selamlık, Harem + Painting Museum"},photoSpot:{free:"Crystal Staircase from the ground floor looking up is the classic shot."},timeReality:{quick:"1.5h (Selamlık only)",ideal:"2.5–3h (full palace + Harem + museum)",note:"The Harem is worth the extra time."},goodToKnow:["Closed on Mondays","No photography inside the palace","Guided tour mandatory and included","Shoe covers provided at entrance"],commonMistakes:["Going on Monday (closed)","Only seeing Selamlık","Not booking timed entry","Underestimating the walking distance"],smartPrice:{gate:"€28 Selamlık only",better:"Full: Selamlık + Harem",why:"The Harem rooms are the most impressive"},nearby:["cruise","galata"],comboTip:"Walk along Bosphorus to Ortaköy after for kumpir"},
  dervish:{gallery:["/dervish.jpg","/dervish-2.jpg","/dervish-3.jpg","/dervish-4.jpg"],reviews:"15K+",whyGo:"Not a tourist show — a genuine 800-year-old spiritual practice. Quiet, hypnotic, and deeply moving. Nothing else on your trip will feel like this.",facts:[{l:"From",v:"€22"},{l:"Duration",v:"1h"},{l:"Area",v:"Various"},{l:"Rating",v:"4.9 ⭐"}],bestTime:["Evening ceremonies only","Book a few days ahead","Arrive 20–30 min early for best seats"],skipStrategy:{free:"Popular ceremonies sell out fast. Book in advance.",premium:"Best venue comparison + seating tips"},photoSpot:{free:"Photos only before and after. No flash during ceremony."},timeReality:{quick:"45 min (ceremony)",ideal:"1h+ (with pre-show context)",note:"Arrive early to settle in."},goodToKnow:["Silence during ceremony is expected","No photography during whirling","Dress modestly and respectfully","Different venues have different vibes"],commonMistakes:["Booking a tourist-oriented venue","Arriving late (may not get in)","Taking flash photos during ceremony","Treating it like entertainment"],smartPrice:{gate:"€22 standard",better:"Respected venue with good acoustics",why:"The venue makes a huge difference"},nearby:["hagia","basilica"],comboTip:"Perfect evening activity — pair with dinner nearby"},
  islands:{gallery:["/islands.jpg","/islands-2.jpg","/islands-3.jpg","/islands-4.jpg"],reviews:"22K+",whyGo:"Istanbul's slower side in one day. No cars, no traffic — just sea breeze, pine trees, and a completely different pace.",facts:[{l:"From",v:"€35"},{l:"Duration",v:"Full day"},{l:"Area",v:"Sea of Marmara"},{l:"Rating",v:"4.7 ⭐"}],bestTime:["Weekdays for fewer crowds","First ferry for maximum island time","Spring and early autumn are ideal"],skipStrategy:{free:"Take the fast ferry from Kabataş. Focus on one island first time.",premium:"Island comparison + local lunch spots"},photoSpot:{free:"Victorian mansions on the hill roads + pine forest trails."},timeReality:{quick:"Half day (rush — not ideal)",ideal:"Full day (ferry + explore + lunch)",note:"This is a day trip — don't squeeze it."},goodToKnow:["Electric vehicles replaced horse carriages","Last ferry back around 20:00","Bring sunscreen and comfortable shoes","Büyükada is the main island"],commonMistakes:["Going on a weekend (very crowded)","Trying to visit multiple islands","Taking a late ferry out","Not checking return ferry times"],smartPrice:{gate:"€35 guided tour",better:"Tour with ferry + lunch",why:"Covers logistics so you can just enjoy"},nearby:["cruise","maiden"],comboTip:"Best as a standalone day trip"},
  cooking:{gallery:["/cooking.jpg","/cooking-2.jpg","/cooking-3.jpg","/cooking-4.jpg"],reviews:"8K+",whyGo:"Way more memorable than another standard dinner. Shop, cook, and feast with a local host — skills you take home as the best souvenir.",facts:[{l:"From",v:"€50"},{l:"Duration",v:"3–4h"},{l:"Area",v:"Various"},{l:"Rating",v:"4.9 ⭐"}],bestTime:["Morning classes include market visit","Book 2–3 days ahead","Weekday classes tend to be smaller"],skipStrategy:{free:"Choose a class with market visit + small group.",premium:"Best class comparison + what to look for"},photoSpot:{free:"Market visit and final feast presentation are the most photogenic."},timeReality:{quick:"2h (kitchen only — less interesting)",ideal:"4h (market + cooking + feast)",note:"The market visit makes the whole experience."},goodToKnow:["Vegetarian options usually available","Come hungry — you'll eat a full meal","You learn recipes for home","Most classes in Sultanahmet or Kadıköy"],commonMistakes:["Booking a demo-only class","Choosing a large group class","Skipping the market visit option","Eating a big breakfast before"],smartPrice:{gate:"€50 kitchen only",better:"Full-day with market visit",why:"The market context makes cooking meaningful"},nearby:["foodtour","hammam"],comboTip:"Morning cooking class + afternoon sightseeing"},
  foodtour:{gallery:["/foodtour.jpg","/foodtour-2.jpg","/foodtour-3.jpg","/foodtour-4.jpg"],reviews:"12K+",whyGo:"The fastest way to understand Istanbul through food. From simit to meyhane plates — the food scene tourists usually miss.",facts:[{l:"From",v:"€40"},{l:"Duration",v:"3–3.5h"},{l:"Area",v:"Various"},{l:"Rating",v:"4.8 ⭐"}],bestTime:["Lunch tours are the most energetic","Come hungry — you'll eat a lot","Kadıköy for local energy, Eminönü for classics"],skipStrategy:{free:"Show up hungry and wear comfortable walking shoes.",premium:"Best route comparison + restaurant insider tips"},photoSpot:{free:"Street food prep and market stalls make the best content."},timeReality:{quick:"2h (abbreviated — less variety)",ideal:"3.5h (8–10 stops, full experience)",note:"Don't book a heavy dinner right after."},goodToKnow:["8–10 tasting stops included","Comfortable walking shoes essential","Most tours run rain or shine","Great way to orient in a new neighborhood"],commonMistakes:["Eating before the tour","Wearing uncomfortable shoes","Booking a heavy dinner right after","Not choosing the right neighborhood"],smartPrice:{gate:"€40 standard",better:"Tour with local guide + 8–10 stops",why:"The guide context turns snacks into stories"},nearby:["cooking","cruise"],comboTip:"Kadıköy food tour → ferry back → sunset from Eminönü"},
  hoponoff:{gallery:["/hoponoff.jpg","/hoponoff-2.jpg","/hoponoff-3.jpg"],reviews:"9K+",whyGo:"A low-effort way to get your bearings on day one. Open-top views and audio guide give you the city overview before you dive deeper.",facts:[{l:"From",v:"€28"},{l:"Duration",v:"Full day"},{l:"Area",v:"City-wide"},{l:"Rating",v:"4.4 ⭐"}],bestTime:["Start early for a top-deck seat","Morning loops before traffic builds","Best on your first or second day"],skipStrategy:{free:"48-hour ticket gives better value than single day.",premium:"Optimal stop strategy + which loops to skip"},photoSpot:{free:"Open top deck gives elevated angles of every major landmark."},timeReality:{quick:"1 full loop (2–3h)",ideal:"Full day (hop on/off at key stops)",note:"Use it strategically as transport."},goodToKnow:["Audio guide in 10+ languages","2 routes covering different areas","Sunscreen essential for open top","Traffic can slow afternoon loops"],commonMistakes:["Using it as primary transport (too slow)","Not starting early enough","Sitting inside on the lower deck","Only buying single-day pass"],smartPrice:{gate:"€28 single day",better:"48-hour pass",why:"Second day is practically free"},nearby:["hagia","galata"],comboTip:"Best as first-day orientation, not main transport"},
  nightcruise:{gallery:["/nightcruise.jpg","/nightcruise-2.jpg","/nightcruise-3.jpg"],reviews:"7K+",whyGo:"City lights, bridge glow, and a Bosphorus breeze make this the easiest date-night win in Istanbul.",facts:[{l:"From",v:"€55"},{l:"Duration",v:"3h"},{l:"Area",v:"Eminönü"},{l:"Rating",v:"4.6 ⭐"}],bestTime:["Book for a clear evening","Weekend cruises have more atmosphere","Arrive 30 min early for best seats"],skipStrategy:{free:"Double-check what's included before booking.",premium:"Best cruise comparison + which upgrades are worth it"},photoSpot:{free:"Illuminated mosques and bridge reflections from the open deck."},timeReality:{quick:"2h (shorter cruises exist)",ideal:"3h (dinner + show + full route)",note:"This is an evening plan, not a quick activity."},goodToKnow:["Smart casual dress code","Arrive 30 min early for boarding","Vegetarian menus available on request","Bring a layer — cool on deck at night"],commonMistakes:["Not checking what's included","Going to the wrong pier","Expecting fine dining (it's good, not Michelin)","Not requesting a window table"],smartPrice:{gate:"€55 standard",better:"Package with window seat + drinks",why:"Only worth it if window seating is guaranteed"},nearby:["cruise","galata"],comboTip:"Explore Eminönü or Karaköy before boarding"},
  aquarium:{gallery:["/aquarium.jpg","/aquarium-2.jpg","/aquarium-3.jpg"],reviews:"14K+",whyGo:"Rainy-day hero for families. Sharks, tunnels, themed zones, and an easy half-day plan when kids need a guaranteed win.",facts:[{l:"From",v:"€22"},{l:"Duration",v:"1.5–2h"},{l:"Area",v:"Florya"},{l:"Rating",v:"4.5 ⭐"}],bestTime:["Weekday mornings are calmest","Avoid weekends and school holidays","After lunch is usually quieter"],skipStrategy:{free:"Weekday morning visit avoids most crowds.",premium:"Combo deals + skip-the-line strategy"},photoSpot:{free:"Shark tunnel walkway and tropical zone are the best spots."},timeReality:{quick:"1h (walk-through only)",ideal:"2h (all zones + touch pools)",note:"Kids will want more time than you think."},goodToKnow:["16 themed zones from Black Sea to Pacific","Touch pools for kids","Food court and mall in same complex","Stroller-friendly throughout"],commonMistakes:["Going on a weekend (packed)","Not planning enough time","Skipping the touch pool area","Not checking combo deals"],smartPrice:{gate:"€22 standard",better:"Combo with Aqua Florya",why:"More to do for same-area visit"},nearby:["islands","hoponoff"],comboTip:"Pair with Florya beach walk if weather improves"},
  maiden:{gallery:["/maiden.jpg","/maiden-2.jpg","/maiden-3.jpg","/maiden-4.jpg"],reviews:"20K+",whyGo:"Right in the middle of the sea. It's not about size — it's about the feeling. Recently restored and more beautiful than ever.",facts:[{l:"From",v:"€20"},{l:"Duration",v:"1–1.5h"},{l:"Area",v:"Üsküdar"},{l:"Rating",v:"4.7 ⭐"}],bestTime:["Late afternoon for sunset views","Midday for cleaner photos, fewer crowds","Reserve ferry slot in advance"],skipStrategy:{free:"Access is capacity-controlled. Reserve the ferry slot in advance.",premium:"Best time slot + photography timing strategy"},photoSpot:{free:"Café terrace looking back toward the old city skyline."},timeReality:{quick:"45 min (tower + quick look)",ideal:"1.5h (museum + café + sunset)",note:"The café tea with a view is worth staying for."},goodToKnow:["Recently restored and reopened","Small museum inside about its history","Boats from Üsküdar and Kabataş every 15 min","Café serves Turkish tea with a view"],commonMistakes:["Not booking the ferry in advance","Going on a hazy day (view is key)","Rushing through without café stop","Missing the museum inside"],smartPrice:{gate:"€20 ferry + tower",better:"Pre-booked combo slot",why:"Guaranteed entry — walk-ups risk being turned away"},nearby:["cruise","islands"],comboTip:"Üsküdar waterfront → Maiden's Tower → sunset"},
};

export default function AttractionSheet({ attraction, allAttractions, onClose, onFav, isFav, onOpenOther, isPremium, onUpgrade, onBook }) {
  const [gi, setGi] = useState(0);
  const [vis, setVis] = useState(false);
  useEffect(() => { if (attraction) setTimeout(() => setVis(true), 10); return () => setVis(false); }, [attraction?.id]);
  if (!attraction) return null;
  const d = D[attraction.id] || {};
  const gallery = d.gallery || [attraction.img];
  const img = gallery[gi] || gallery[0];
  const nearby = (d.nearby || []).map(id => (allAttractions || []).find(a => a.id === id)).filter(Boolean);
  const handleClose = () => { setVis(false); setTimeout(onClose, 250); };
  const handleNearby = (n) => { setGi(0); setVis(false); setTimeout(() => { if (onOpenOther) onOpenOther(n); setTimeout(() => setVis(true), 50); }, 200); };
  const Sec = ({ children, bg = "white" }) => (<div style={{ borderRadius: 20, border: `1px solid ${C.line}`, background: bg, padding: 16, marginBottom: 10 }}>{children}</div>);
  const ST = ({ icon: Icon, children }) => (<div style={{ display: "flex", alignItems: "center", gap: 8, marginBottom: 10 }}>{Icon && <Icon size={16} color={C.ink} strokeWidth={1.8} />}<span style={{ fontSize: 14, fontWeight: 800, color: C.ink }}>{children}</span></div>);
  const Bul = ({ children, icon = "→" }) => (<div style={{ display: "flex", gap: 8, padding: "3px 0", fontSize: 13, color: C.inkSoft, lineHeight: 1.6 }}><span style={{ color: C.inkMute, flexShrink: 0 }}>{icon}</span><span>{children}</span></div>);

  return (
    <div style={{ position: "fixed", inset: 0, zIndex: 300, fontFamily: fs, display: "flex", flexDirection: "column", alignItems: "center", background: "rgba(15,23,42,0.5)", backdropFilter: "blur(4px)", transition: "opacity 0.25s", opacity: vis ? 1 : 0 }}>
      <div style={{ width: "100%", maxWidth: 440, height: "100%", display: "flex", flexDirection: "column", background: "white", transform: vis ? "translateY(0)" : "translateY(40px)", transition: "transform 0.3s cubic-bezier(0.32,0.72,0,1)" }}>
        {/* 1. HERO */}
        <div style={{ position: "relative", height: 280, overflow: "hidden", flexShrink: 0 }}>
          <img src={img} alt={attraction.title} style={{ width: "100%", height: "100%", objectFit: "cover" }} />
          <div style={{ position: "absolute", inset: 0, background: "linear-gradient(to top, rgba(15,23,42,0.65), rgba(15,23,42,0.05))" }} />
          <div style={{ position: "absolute", top: 14, left: 14, right: 14, display: "flex", justifyContent: "space-between", alignItems: "center" }}>
            <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
              <button onClick={handleClose} style={{ width: 40, height: 40, borderRadius: 16, border: "none", background: "rgba(0,0,0,0.3)", backdropFilter: "blur(12px)", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" }}><ArrowLeft size={16} color="white" /></button>
              {attraction.hook && <div style={{ background: "rgba(197,157,95,0.9)", color: "white", padding: "4px 10px", borderRadius: 8, fontSize: 10, fontWeight: 700 }}>{attraction.hook}</div>}
            </div>
            <button onClick={() => onFav && onFav(attraction.id)} style={{ width: 40, height: 40, borderRadius: 16, border: "none", background: isFav ? "rgba(225,29,72,0.85)" : "rgba(0,0,0,0.3)", backdropFilter: "blur(12px)", display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer" }}><Heart size={16} color="white" fill={isFav ? "white" : "none"} /></button>
          </div>
          <div style={{ position: "absolute", left: 16, bottom: 16, right: 16 }}>
            <div style={{ display: "flex", gap: 6, marginBottom: 8 }}>
              <span style={{ background: "rgba(255,255,255,0.2)", color: "white", padding: "3px 8px", borderRadius: 6, fontSize: 10, fontWeight: 700 }}>{attraction.badge}</span>
              {attraction.skip && <span style={{ background: "rgba(5,150,105,0.8)", color: "white", padding: "3px 8px", borderRadius: 6, fontSize: 10, fontWeight: 700 }}>⚡ Skip line</span>}
            </div>
            <div style={{ fontSize: 26, fontWeight: 800, letterSpacing: "-0.04em", color: "white", fontFamily: fd }}>{attraction.title}</div>
            <div style={{ marginTop: 4, fontSize: 13, color: "rgba(255,255,255,0.75)", lineHeight: 1.5 }}>{attraction.teaser}</div>
          </div>
        </div>
        {/* SCROLLABLE */}
        <div style={{ flex: 1, overflowY: "auto", padding: "14px 16px 20px", background: "linear-gradient(180deg,#F8FBFF 0%,#F5F7FB 30%)" }}>
          {gallery.length > 1 && <div style={{ display: "flex", gap: 6, overflowX: "auto", paddingBottom: 6, marginBottom: 10 }}>{gallery.map((im, i) => <button key={i} onClick={() => setGi(i)} style={{ width: 52, height: 52, borderRadius: 12, overflow: "hidden", flexShrink: 0, padding: 0, cursor: "pointer", border: gi === i ? `2px solid ${C.blue}` : `1px solid ${C.line}`, background: "white" }}><img src={im} alt="" style={{ width: "100%", height: "100%", objectFit: "cover" }} /></button>)}</div>}
          {/* 2. WHY */}
          {d.whyGo && <Sec><ST icon={Landmark}>Why this place</ST><div style={{ fontSize: 13, lineHeight: 1.7, color: C.inkSoft }}>{d.whyGo}</div></Sec>}
          {/* 3. FACTS */}
          {d.facts && <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 10 }}>{d.facts.map(f => <div key={f.l} style={{ borderRadius: 14, border: `1px solid ${C.line}`, background: "white", padding: "10px 12px" }}><div style={{ fontSize: 10, color: C.inkMute, textTransform: "uppercase", letterSpacing: "0.06em" }}>{f.l}</div><div style={{ marginTop: 3, fontSize: 14, fontWeight: 800 }}>{f.v}</div></div>)}</div>}
          {/* 4. BEST TIME */}
          {d.bestTime && <Sec bg="linear-gradient(135deg,#EFF6FF,#F8FAFC)"><ST icon={Clock}>Best time to go</ST>{d.bestTime.map((t, i) => <Bul key={i} icon={i === 0 ? "✅" : i === d.bestTime.length - 1 ? "🚫" : "💡"}>{t}</Bul>)}</Sec>}
          {/* 5. SKIP STRATEGY */}
          {d.skipStrategy && <Sec><ST icon={Zap}>Skip-the-line strategy</ST><div style={{ fontSize: 13, lineHeight: 1.6, color: C.inkSoft, marginBottom: 8 }}>{d.skipStrategy.free}</div>{!isPremium && d.skipStrategy.premium && <div onClick={() => onUpgrade && onUpgrade()} style={{ display: "flex", alignItems: "center", gap: 8, padding: "8px 10px", borderRadius: 10, background: C.goldSoft, cursor: "pointer" }}><span style={{ fontSize: 12 }}>✨</span><span style={{ fontSize: 11, color: C.gold, fontWeight: 600, flex: 1 }}>Insider strategy: {d.skipStrategy.premium}</span><span style={{ fontSize: 10, color: C.gold }}>→</span></div>}</Sec>}
          {/* 6. PHOTO */}
          {d.photoSpot && <Sec><ST icon={Camera}>Photo spot</ST><div style={{ fontSize: 13, lineHeight: 1.6, color: C.inkSoft }}>{d.photoSpot.free}</div></Sec>}
          {/* 8. TIME REALITY */}
          {d.timeReality && <Sec><ST icon={Clock}>How much time do you need?</ST><div style={{ display: "flex", gap: 8, marginBottom: 8 }}><div style={{ flex: 1, borderRadius: 12, background: C.warnSoft, padding: "8px 10px" }}><div style={{ fontSize: 10, color: C.warn, fontWeight: 600 }}>⚡ Quick</div><div style={{ fontSize: 12, fontWeight: 700, marginTop: 2 }}>{d.timeReality.quick}</div></div><div style={{ flex: 1, borderRadius: 12, background: C.okSoft, padding: "8px 10px" }}><div style={{ fontSize: 10, color: C.ok, fontWeight: 600 }}>🧠 Ideal</div><div style={{ fontSize: 12, fontWeight: 700, marginTop: 2 }}>{d.timeReality.ideal}</div></div></div><div style={{ fontSize: 12, color: C.inkSoft, fontStyle: "italic" }}>{d.timeReality.note}</div></Sec>}
          {/* 9. GOOD TO KNOW */}
          {d.goodToKnow && <Sec><ST icon={Info}>Good to know</ST>{d.goodToKnow.map((t, i) => <Bul key={i} icon="•">{t}</Bul>)}</Sec>}
          {/* BONUS: COMMON MISTAKES */}
          {d.commonMistakes && <Sec bg="linear-gradient(135deg,#FEF2F2,#FFF)"><ST icon={AlertTriangle}>Common mistakes</ST>{d.commonMistakes.map((m, i) => <Bul key={i} icon="❌">{m}</Bul>)}</Sec>}
          {/* 10. SMART PRICE */}
          {d.smartPrice && <Sec><ST icon={Ticket}>Smart ticket choice</ST><div style={{ display: "flex", gap: 8, marginBottom: 8 }}><div style={{ flex: 1, borderRadius: 12, border: `1px solid ${C.line}`, padding: 10, textAlign: "center" }}><div style={{ fontSize: 10, color: C.inkMute }}>Gate ticket</div><div style={{ fontSize: 14, fontWeight: 800, marginTop: 2 }}>{d.smartPrice.gate}</div></div><div style={{ flex: 1, borderRadius: 12, background: C.blueSoft, padding: 10, textAlign: "center" }}><div style={{ fontSize: 10, color: C.blue, fontWeight: 600 }}>Better option</div><div style={{ fontSize: 14, fontWeight: 800, marginTop: 2, color: C.blue }}>{d.smartPrice.better}</div></div></div><div style={{ fontSize: 12, color: C.inkSoft }}>💡 {d.smartPrice.why}</div></Sec>}
          {/* 7. NEARBY */}
          {nearby.length > 0 && <Sec><ST icon={Navigation}>Perfect combo route</ST>{d.comboTip && <div style={{ fontSize: 12, color: C.blue, fontWeight: 600, marginBottom: 10 }}>💡 {d.comboTip}</div>}{nearby.map(n => <div key={n.id} onClick={() => handleNearby(n)} style={{ display: "flex", alignItems: "center", gap: 10, padding: "8px 0", borderTop: `1px solid ${C.line}`, cursor: "pointer" }}><img src={n.img} alt={n.title} style={{ width: 44, height: 44, borderRadius: 12, objectFit: "cover" }} /><div style={{ flex: 1 }}><div style={{ fontSize: 13, fontWeight: 700 }}>{n.title}</div><div style={{ fontSize: 11, color: C.inkMute }}>{n.cat} · €{n.price}</div></div><ChevronRight size={14} color={C.inkMute} /></div>)}</Sec>}
          {/* 11. PREMIUM BAIT */}
          {!isPremium && <div onClick={() => onUpgrade && onUpgrade()} style={{ display: "flex", alignItems: "center", gap: 10, padding: "10px 14px", borderRadius: 14, background: C.soft, border: `1px solid ${C.line}`, marginBottom: 10, cursor: "pointer" }}><span style={{ fontSize: 15 }}>✨</span><div style={{ flex: 1, fontSize: 12, color: C.inkSoft }}>Want a full day built around this? <span style={{ fontWeight: 700, color: C.ink }}>Get your personalized route</span></div><span style={{ fontSize: 10, color: C.gold }}>→</span></div>}
        </div>
        {/* 12. STICKY CTA */}
        <div style={{ flexShrink: 0, borderTop: `1px solid ${C.line}`, background: "rgba(255,255,255,0.97)", backdropFilter: "blur(10px)", padding: "10px 16px 18px" }}>
          <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 8 }}>
            <span style={{ fontSize: 10, color: C.warn, fontWeight: 600 }}>⏳ Sells out in peak season</span>
          </div>
          <div style={{ display: "flex", alignItems: "center", gap: 8 }}>
            <div style={{ flex: "0 0 auto" }}>
              <div style={{ fontSize: 10, color: C.inkMute }}>From</div>
              <div style={{ fontSize: 22, fontWeight: 800, letterSpacing: "-0.03em" }}>€{attraction.price}</div>
            </div>
            <div onClick={() => { if (onFav) onFav(attraction.id); }} style={{ display: "flex", alignItems: "center", justifyContent: "center", gap: 4, padding: "12px 14px", borderRadius: 14, border: `1.5px solid ${C.line}`, fontSize: 12, fontWeight: 600, color: C.ink, cursor: "pointer", background: "white" }}>+ My Day</div>
            <div onClick={() => onBook && onBook(attraction)} style={{ flex: 1, border: "none", background: "linear-gradient(135deg,#1D4ED8,#1E40AF)", color: "white", borderRadius: 14, padding: "12px 0", fontSize: 13, fontWeight: 700, cursor: "pointer", display: "flex", alignItems: "center", justifyContent: "center", gap: 6, boxShadow: "0 4px 14px rgba(29,78,216,0.3)", textAlign: "center" }}>{attraction.skip ? "Skip the Line →" : "Reserve Your Spot →"}</div>
          </div>
        </div>
      </div>
    </div>
  );
}