import { useState, useEffect } from "react";
import {
  ArrowLeft, Heart, Ticket, Star, Info, ChevronRight, Landmark,
  TramFront, Shirt, ExternalLink, Waves, Music, Eye, Moon,
  Ship, Sun, Bus, MapPin, UtensilsCrossed, ChefHat, Fish
} from "lucide-react";

const T = {
  surface:"#FFFFFF",soft:"#F8FAFC",line:"#E2E8F0",
  text:"#0F172A",textSoft:"#475569",textMute:"#94A3B8",
  blue:"#1D4ED8",blueSoft:"#DBEAFE",ok:"#059669",
  warn:"#D97706",dark:"#0F172A",danger:"#E11D48",
};
const fd="'Plus Jakarta Sans',system-ui,sans-serif";
const fs="'Inter',system-ui,sans-serif";

const Pill=({children,tone=T.blueSoft,color=T.blue})=><span style={{display:"inline-flex",alignItems:"center",gap:4,borderRadius:999,padding:"4px 10px",background:tone,color,fontSize:11,fontWeight:700}}>{children}</span>;

const DETAILS = {
  hagia:{gallery:["/hagia.jpg","/hagia-2.jpg","/hagia-3.jpg","/hagia-4.jpg","/hagia-5.jpg"],reviews:"48K+",intro:"One of Istanbul's most iconic landmarks, Hagia Sophia brings together Byzantine grandeur and Ottoman history in one unforgettable space.",ticketTip:"Go early, especially on Fridays. Tourist access may pause around prayer times — morning is the smoothest window.",facts:[{l:"Open",v:"09:00–19:00"},{l:"Best time",v:"Before 10:00"},{l:"Duration",v:"1–1.5h"},{l:"Ticket",v:"€25"}],sections:[{title:"Why visit?",icon:Landmark,content:"The dome, mosaics, and layered religious history make it worth prioritizing even on a short trip."},{title:"How to get there",icon:TramFront,content:"Tram T1 to Sultanahmet. Very short walk from the stop."},{title:"Know before you go",icon:Shirt,content:"Modest clothing required. Museum Pass not valid here."}],nearby:["basilica","topkapi"]},
  basilica:{gallery:["/basilica.jpg","/basilica-2.jpg","/basilica-3.jpg","/basilica-4.jpg"],reviews:"32K+",intro:"An underground wonder with 336 marble columns, atmospheric lighting, and the famous Medusa heads.",ticketTip:"Book skip-the-line online — queues can be 30–45 min. Late afternoon is quieter.",facts:[{l:"Open",v:"09:00–18:30"},{l:"Best time",v:"After 15:00"},{l:"Duration",v:"45min–1h"},{l:"Ticket",v:"€20"}],sections:[{title:"Why visit?",icon:Landmark,content:"Atmospheric columns and water reflections create a truly unique experience."},{title:"How to get there",icon:TramFront,content:"Tram T1 to Sultanahmet, 3-minute walk. Between Hagia Sophia and Blue Mosque."},{title:"Know before you go",icon:Info,content:"Cool underground — great in summer. Small café inside. No flash photography."}],nearby:["hagia","topkapi"]},
  topkapi:{gallery:["/topkapi.jpg","/topkapi-2.jpg","/topkapi-3.jpg","/topkapi-4.jpg"],reviews:"41K+",intro:"The main Ottoman sultan residence for 400 years. Stunning courtyards, Imperial Treasury, and panoramic Bosphorus views.",ticketTip:"Harem needs separate ticket — buy combo. Arrive at opening, crowded by 11:00.",facts:[{l:"Open",v:"09:00–18:00"},{l:"Best time",v:"At opening"},{l:"Duration",v:"2–3h"},{l:"Ticket",v:"€30"}],sections:[{title:"Why visit?",icon:Landmark,content:"Ottoman wealth on full display. Treasury alone is worth it. Fourth courtyard Bosphorus views are spectacular."},{title:"How to get there",icon:TramFront,content:"Tram T1 to Gülhane or Sultanahmet."},{title:"Know before you go",icon:Info,content:"Closed Tuesdays. Harem separate ticket. Wear comfortable shoes."}],nearby:["hagia","basilica"]},
  cruise:{gallery:["/cruise.jpg","/cruise-2.jpg","/cruise-3.jpg","/cruise-4.jpg"],reviews:"28K+",intro:"See Istanbul from the water — palaces, fortresses, and skyline between two continents. Sunset departures are magical.",ticketTip:"Book late afternoon for sunset. Sit right side going up for European palaces.",facts:[{l:"Departs",v:"Multiple daily"},{l:"Best time",v:"Sunset"},{l:"Duration",v:"1.5–2h"},{l:"Ticket",v:"€18"}],sections:[{title:"Why visit?",icon:Waves,content:"Best way to understand Istanbul's geography. See Dolmabahçe, bridges, Rumeli Fortress from the water."},{title:"How to get there",icon:TramFront,content:"Most depart from Eminönü or Kabataş. Tram T1 to Eminönü."},{title:"Know before you go",icon:Info,content:"Bring a jacket — breezy on water. Small café on board."}],nearby:["galata","dolma"]},
  hammam:{gallery:["/hammam.jpg","/hammam-2.jpg","/hammam-3.jpg","/hammam-4.jpg"],reviews:"18K+",intro:"Centuries-old bathing tradition — steam, marble, and a proper scrub. Part relaxation, part cultural experience.",ticketTip:"Book traditional package (scrub + foam). Kılıç Ali Paşa offers the best experience.",facts:[{l:"Duration",v:"60–90min"},{l:"Best time",v:"Morning"},{l:"Type",v:"Traditional"},{l:"Ticket",v:"From €45"}],sections:[{title:"Why visit?",icon:Waves,content:"One of those defining Istanbul experiences. Hot marble, steam, and vigorous scrub leave you renewed."},{title:"How to get there",icon:TramFront,content:"Çemberlitaş nearest to Sultanahmet. Kılıç Ali Paşa in Tophane."},{title:"Know before you go",icon:Shirt,content:"Peştamal (wrap) provided. Swimwear optional. Separate sections men/women."}],nearby:["hagia","basilica"]},
  galata:{gallery:["/galata.jpg","/galata-2.jpg","/galata-3.jpg","/galata-4.jpg"],reviews:"35K+",intro:"Medieval stone tower with the best 360° panoramic view of Istanbul.",ticketTip:"Buy online to skip queue. Go for sunset — unforgettable light over old city.",facts:[{l:"Open",v:"08:30–23:00"},{l:"Best time",v:"Sunset"},{l:"Duration",v:"30–45min"},{l:"Ticket",v:"€15"}],sections:[{title:"Why visit?",icon:Eye,content:"The view is worth it alone. Perfect pre-dinner stop."},{title:"How to get there",icon:TramFront,content:"Walk up from Karaköy or take Tünel funicular. Short walk from İstiklal."},{title:"Know before you go",icon:Info,content:"Elevator inside. Open-air observation deck can get crowded."}],nearby:["cruise","dolma"]},
  dolma:{gallery:["/dolma.jpg","/dolma-2.jpg","/dolma-3.jpg","/dolma-4.jpg"],reviews:"29K+",intro:"Last imperial Ottoman palace on the Bosphorus. Crystal Staircase and 4.5-ton chandelier are jaw-dropping.",ticketTip:"Book timed entry online — walk-up queues can be an hour. Full ticket worth it.",facts:[{l:"Open",v:"09:00–18:00"},{l:"Best time",v:"Morning"},{l:"Duration",v:"1.5–2h"},{l:"Ticket",v:"€28"}],sections:[{title:"Why visit?",icon:Landmark,content:"Ottoman ambition on display. European-style interiors, crystal chandeliers, Bosphorus-front setting."},{title:"How to get there",icon:TramFront,content:"Tram T1 to Kabataş, short waterfront walk."},{title:"Know before you go",icon:Info,content:"Closed Mondays. No photography inside. Guided tour mandatory."}],nearby:["cruise","galata"]},
  dervish:{gallery:["/dervish.jpg","/dervish-2.jpg","/dervish-3.jpg","/dervish-4.jpg"],reviews:"15K+",intro:"Mesmerizing Sufi ceremony — spinning as meditation. Spiritual, beautiful, unique to Turkey.",ticketTip:"Book in advance — sells out. Hodjapasha and Galata Mevlevihane are best venues.",facts:[{l:"Shows",v:"Evening"},{l:"Best venue",v:"Hodjapasha"},{l:"Duration",v:"1h"},{l:"Ticket",v:"€22"}],sections:[{title:"Why visit?",icon:Music,content:"Not a tourist show — genuine 800-year-old spiritual practice. Deeply moving."},{title:"How to get there",icon:TramFront,content:"Hodjapasha near Sirkeci (Tram T1). Mevlevihane near İstiklal."},{title:"Know before you go",icon:Info,content:"Silence expected. No photos during whirling. Dress respectfully. Arrive 15 min early."}],nearby:["hagia","basilica"]},
  islands:{gallery:["/islands.jpg","/islands-2.jpg","/islands-3.jpg","/islands-4.jpg"],reviews:"22K+",intro:"Car-free islands — pine forests, Victorian mansions, best seafood lunch in Istanbul.",ticketTip:"Guided tour recommended first time. Büyükada is the main island.",facts:[{l:"Ferry",v:"From Kabataş"},{l:"Best time",v:"Weekday"},{l:"Duration",v:"Full day"},{l:"Ticket",v:"€35"}],sections:[{title:"Why visit?",icon:Sun,content:"Perfect city escape. No cars, sea breeze, pine trees, different pace."},{title:"How to get there",icon:Ship,content:"Fast ferry from Kabataş, ~40 min to Büyükada."},{title:"Know before you go",icon:Info,content:"Weekdays less crowded. Electric vehicles replaced horses. Last ferry ~20:00."}],nearby:["cruise","maiden"]},
  cooking:{gallery:["/cooking.jpg","/cooking-2.jpg","/cooking-3.jpg","/cooking-4.jpg"],reviews:"8K+",intro:"Learn manti to baklava with a local chef. Market visit, cook together, eat everything.",ticketTip:"Book full-day with market visit — much richer experience.",facts:[{l:"Includes",v:"Market + meal"},{l:"Best time",v:"Morning"},{l:"Duration",v:"3–4h"},{l:"Ticket",v:"€50"}],sections:[{title:"Why visit?",icon:ChefHat,content:"Food is central to Turkish culture. Best way to understand it. Learn techniques for home."},{title:"How to get there",icon:TramFront,content:"Most classes in Sultanahmet or Kadıköy. Host sends meeting point."},{title:"Know before you go",icon:Info,content:"Vegetarian options available. Come hungry."}],nearby:["foodtour","hammam"]},
  foodtour:{gallery:["/foodtour.jpg","/foodtour-2.jpg","/foodtour-3.jpg","/foodtour-4.jpg"],reviews:"12K+",intro:"Taste through Istanbul's neighborhoods with a local guide. Street simit to hidden meyhane gems.",ticketTip:"Kadıköy tour for Asian side. Sultanahmet/Eminönü for classic spots.",facts:[{l:"Stops",v:"8–10 tastings"},{l:"Best time",v:"Lunch"},{l:"Duration",v:"3–4h"},{l:"Ticket",v:"€40"}],sections:[{title:"Why visit?",icon:UtensilsCrossed,content:"Discover places not in guidebooks. Local context makes each bite meaningful."},{title:"How to get there",icon:TramFront,content:"Meeting points vary by tour."},{title:"Know before you go",icon:Info,content:"Come hungry. Comfortable shoes. Rain or shine."}],nearby:["cooking","cruise"]},
  hoponoff:{gallery:["/hoponoff.jpg","/hoponoff-2.jpg","/hoponoff-3.jpg"],reviews:"9K+",intro:"Open-top bus covering main sights. Audio guide in 10+ languages. Great first-day orientation.",ticketTip:"48-hour ticket better value. Use as transport between sights.",facts:[{l:"Routes",v:"2 loops"},{l:"Frequency",v:"Every 30min"},{l:"Duration",v:"Full day"},{l:"Ticket",v:"€28"}],sections:[{title:"Why visit?",icon:Bus,content:"First-time overview. Open top great for photos."},{title:"How to get there",icon:MapPin,content:"Stops at Sultanahmet, Taksim, Eminönü."},{title:"Know before you go",icon:Info,content:"Sunscreen for open top. Traffic slows afternoons."}],nearby:["hagia","galata"]},
  nightcruise:{gallery:["/nightcruise.jpg","/nightcruise-2.jpg","/nightcruise-3.jpg"],reviews:"7K+",intro:"Candlelit Bosphorus dinner with live music and illuminated skyline.",ticketTip:"Book window table. Premium packages include unlimited drinks.",facts:[{l:"Departs",v:"20:00"},{l:"Includes",v:"Dinner + show"},{l:"Duration",v:"3h"},{l:"Ticket",v:"€55"}],sections:[{title:"Why visit?",icon:Moon,content:"Istanbul at night from the water is mesmerizing. Mosques, bridges, palaces all lit up."},{title:"How to get there",icon:Ship,content:"Most depart Eminönü or Kabataş."},{title:"Know before you go",icon:Shirt,content:"Smart casual. Arrive 30 min early. Bring a layer."}],nearby:["cruise","galata"]},
  aquarium:{gallery:["/aquarium.jpg","/aquarium-2.jpg","/aquarium-3.jpg"],reviews:"14K+",intro:"One of Europe's largest — 16 themed zones, walk-through tunnel, touch pools.",ticketTip:"Weekday mornings quietest. Combo tickets available.",facts:[{l:"Open",v:"10:00–20:00"},{l:"Best for",v:"Families"},{l:"Duration",v:"1.5–2h"},{l:"Ticket",v:"€22"}],sections:[{title:"Why visit?",icon:Fish,content:"Perfect for families or rainy days. Kids love touch pools and shark tunnel."},{title:"How to get there",icon:TramFront,content:"Marmaray/Metrobus to Florya. Inside Aqua Florya complex."},{title:"Know before you go",icon:Info,content:"Plan 2 hours. Food court and mall in same complex."}],nearby:["islands","hoponoff"]},
  maiden:{gallery:["/maiden.jpg","/maiden-2.jpg","/maiden-3.jpg","/maiden-4.jpg"],reviews:"20K+",intro:"Restored tower on its own island between two continents. Museum, café, incredible old city views.",ticketTip:"Book ferry + tower combo online. Café gets busy — go early or late.",facts:[{l:"Open",v:"09:00–18:00"},{l:"Best time",v:"Late afternoon"},{l:"Duration",v:"1–1.5h"},{l:"Ticket",v:"€20"}],sections:[{title:"Why visit?",icon:Landmark,content:"Newly restored. Most photogenic spot. Sunset views toward old city extraordinary."},{title:"How to get there",icon:Ship,content:"Boats from Üsküdar and Kabataş every 15 min."},{title:"Know before you go",icon:Info,content:"Small museum inside. Café serves Turkish tea with a view."}],nearby:["cruise","islands"]},
};

export default function AttractionSheet({attraction, allAttractions, onClose, onFav, isFav, onOpenOther}){
  const[gi,setGi]=useState(0);
  const[visible,setVisible]=useState(false);

  useEffect(()=>{if(attraction)setTimeout(()=>setVisible(true),10);return()=>setVisible(false)},[attraction?.id]);

  if(!attraction) return null;
  const d=DETAILS[attraction.id]||{};
  const gallery=d.gallery||[attraction.img];
  const img=gallery[gi]||gallery[0];
  const nearby=(d.nearby||[]).map(id=>(allAttractions||[]).find(a=>a.id===id)).filter(Boolean);

  const handleClose=()=>{setVisible(false);setTimeout(onClose,250)};
  const handleNearby=(n)=>{setGi(0);setVisible(false);setTimeout(()=>{if(onOpenOther)onOpenOther(n);setTimeout(()=>setVisible(true),50)},200)};

  return(
    <div style={{position:"fixed",inset:0,zIndex:300,fontFamily:fs,display:"flex",flexDirection:"column",alignItems:"center",background:"rgba(15,23,42,0.5)",backdropFilter:"blur(4px)",transition:"opacity 0.25s",opacity:visible?1:0}}>
      <div style={{width:"100%",maxWidth:440,height:"100%",display:"flex",flexDirection:"column",background:T.surface,transform:visible?"translateY(0)":"translateY(40px)",transition:"transform 0.3s cubic-bezier(0.32,0.72,0,1)",position:"relative"}}>

        {/* HERO */}
        <div style={{position:"relative",height:280,overflow:"hidden",flexShrink:0}}>
          <img src={img} alt={attraction.title} style={{width:"100%",height:"100%",objectFit:"cover",transition:"opacity 0.3s"}}/>
          <div style={{position:"absolute",inset:0,background:"linear-gradient(to top,rgba(15,23,42,0.6),rgba(15,23,42,0.05))"}}/>
          <div style={{position:"absolute",top:14,left:14,right:14,display:"flex",justifyContent:"space-between"}}>
            <button onClick={handleClose} style={{width:40,height:40,borderRadius:16,border:"none",background:"rgba(0,0,0,0.3)",backdropFilter:"blur(12px)",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><ArrowLeft size={16} color="white"/></button>
            <button onClick={()=>onFav&&onFav(attraction.id)} style={{width:40,height:40,borderRadius:16,border:"none",background:isFav?"rgba(225,29,72,0.85)":"rgba(0,0,0,0.3)",backdropFilter:"blur(12px)",display:"flex",alignItems:"center",justifyContent:"center",cursor:"pointer"}}><Heart size={16} color="white" fill={isFav?"white":"none"}/></button>
          </div>
          <div style={{position:"absolute",left:16,bottom:16,right:16}}>
            <Pill tone="rgba(255,255,255,0.2)" color="white">{attraction.badge}</Pill>
            <div style={{marginTop:10,fontSize:26,fontWeight:800,letterSpacing:"-0.04em",color:"white",fontFamily:fd}}>{attraction.title}</div>
            <div style={{marginTop:6,display:"flex",flexWrap:"wrap",gap:8,color:"rgba(255,255,255,0.8)",fontSize:12,fontWeight:600}}>
              <span>{attraction.cat}</span><span>·</span><span>{attraction.area||"Istanbul"}</span><span>·</span>
              <span style={{display:"inline-flex",alignItems:"center",gap:3}}><Star size={11} fill="currentColor"/>{attraction.rating}</span>
              {d.reviews&&<><span>·</span><span>{d.reviews} reviews</span></>}
            </div>
          </div>
        </div>

        {/* CONTENT */}
        <div style={{flex:1,overflowY:"auto",padding:"14px 18px 20px",background:"linear-gradient(180deg,#F8FBFF 0%,#F5F7FB 30%)"}}>
          {gallery.length>1&&<div style={{display:"flex",gap:8,overflowX:"auto",paddingBottom:8,marginBottom:12}}>{gallery.map((im,i)=><button key={i} onClick={()=>setGi(i)} style={{width:60,height:60,borderRadius:14,overflow:"hidden",flexShrink:0,padding:0,cursor:"pointer",border:gi===i?`2px solid ${T.blue}`:`1px solid ${T.line}`,background:T.surface}}><img src={im} alt="" style={{width:"100%",height:"100%",objectFit:"cover"}}/></button>)}</div>}

          {d.facts&&<div style={{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12}}>{d.facts.map(f=><div key={f.l} style={{borderRadius:16,border:`1px solid ${T.line}`,background:"white",padding:12}}><div style={{fontSize:10,color:T.textMute,textTransform:"uppercase",letterSpacing:"0.08em"}}>{f.l}</div><div style={{marginTop:3,fontSize:14,fontWeight:800}}>{f.v}</div></div>)}</div>}

          {d.intro&&<div style={{borderRadius:20,background:"white",border:`1px solid ${T.line}`,padding:16,marginBottom:12}}><div style={{fontSize:14,fontWeight:800,marginBottom:6}}>Why visit?</div><div style={{fontSize:13,lineHeight:1.7,color:T.textSoft}}>{d.intro}</div></div>}

          {d.ticketTip&&<div style={{borderRadius:20,background:"linear-gradient(135deg,#EFF6FF,#F8FAFC)",border:`1px solid ${T.line}`,padding:16,marginBottom:12}}><div style={{display:"flex",gap:10,alignItems:"flex-start"}}><div style={{width:38,height:38,borderRadius:12,background:"white",display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><Info size={16} color={T.blue}/></div><div><div style={{fontSize:13,fontWeight:800}}>Ticket tip</div><div style={{marginTop:3,fontSize:12,lineHeight:1.6,color:T.textSoft}}>{d.ticketTip}</div></div></div></div>}

          {d.sections&&d.sections.map(s=><div key={s.title} style={{borderRadius:20,border:`1px solid ${T.line}`,background:"white",padding:16,marginBottom:10}}><div style={{display:"flex",gap:10,alignItems:"flex-start"}}><div style={{width:38,height:38,borderRadius:12,background:T.soft,display:"flex",alignItems:"center",justifyContent:"center",flexShrink:0}}><s.icon size={16} color={T.text}/></div><div><div style={{fontSize:13,fontWeight:800}}>{s.title}</div><div style={{marginTop:4,fontSize:12,lineHeight:1.65,color:T.textSoft}}>{s.content}</div></div></div></div>)}

          {nearby.length>0&&<div style={{marginTop:6,marginBottom:8}}><div style={{fontSize:10,fontWeight:700,letterSpacing:"0.12em",textTransform:"uppercase",color:T.textMute,marginBottom:6}}>Better with combo</div><div style={{fontSize:16,fontWeight:800,fontFamily:fd,marginBottom:10}}>Pair it for a perfect day</div>{nearby.map(n=><div key={n.id} onClick={()=>handleNearby(n)} style={{borderRadius:16,border:`1px solid ${T.line}`,background:"white",padding:10,marginBottom:8,display:"flex",alignItems:"center",gap:10,cursor:"pointer",transition:"transform 0.15s",}}><img src={n.img} alt={n.title} style={{width:48,height:48,borderRadius:12,objectFit:"cover"}}/><div style={{flex:1}}><div style={{fontSize:13,fontWeight:700}}>{n.title}</div><div style={{fontSize:11,color:T.textSoft,marginTop:2}}>{n.cat} · €{n.price}</div></div><ChevronRight size={14} color={T.textMute}/></div>)}</div>}
        </div>

        {/* STICKY CTA */}
        <div style={{flexShrink:0,borderTop:`1px solid ${T.line}`,background:"rgba(255,255,255,0.97)",backdropFilter:"blur(10px)",padding:"10px 16px 18px"}}>
          <div style={{display:"flex",alignItems:"center",justifyContent:"space-between",gap:10}}>
            <div><div style={{fontSize:10,color:T.textMute}}>From</div><div style={{fontSize:22,fontWeight:800,letterSpacing:"-0.03em"}}>€{attraction.price}</div></div>
            <a href={attraction.link} target="_blank" rel="noopener noreferrer" style={{border:"none",background:"linear-gradient(135deg,#1D4ED8,#1E40AF)",color:"white",borderRadius:16,padding:"13px 24px",fontSize:13,fontWeight:700,cursor:"pointer",display:"inline-flex",alignItems:"center",gap:6,textDecoration:"none",boxShadow:"0 4px 14px rgba(29,78,216,0.3)"}}><Ticket size={14}/>Book now</a>
          </div>
        </div>
      </div>
    </div>
  );
}